"""API payload limit 기본값 (ApiSecuritySettings 와 동기화)."""

from __future__ import annotations

DEFAULT_MAX_CHAT_MESSAGE_LENGTH = 4_000
DEFAULT_MAX_RECOMMEND_QUERY_LENGTH = 2_000
DEFAULT_MAX_INGEST_CONTENT_LENGTH = 10_000
DEFAULT_MAX_CYPHER_QUESTION_LENGTH = 2_000

__all__ = [
    "DEFAULT_MAX_CHAT_MESSAGE_LENGTH",
    "DEFAULT_MAX_RECOMMEND_QUERY_LENGTH",
    "DEFAULT_MAX_INGEST_CONTENT_LENGTH",
    "DEFAULT_MAX_CYPHER_QUESTION_LENGTH",
]
